# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDsgydOznGrUmF_d7ELyuePHTcyd5Nzh
"""

import numpy as np
import matplotlib.pyplot as plt


F = np.array([3.406,2.940]) 
L = np.array([0,0]) 
I = np.array([4,0]) 
T = np.array([0.781,2.374])

def line_gen(C1, C2):
    return ((C1[0], C2[0]), (C1[1], C2[1]))

l1 = line_gen(L, I)
l2 = line_gen(I, T)
l3 = line_gen(L, F)
l4 = line_gen(T, F)
l5 = line_gen(T, L)
l6 = line_gen(I, F)

def drawLine(line):
    plt.plot(line[0], line[1])
    
def drawVertix(coordinate, name):
    plt.plot(coordinate[0], coordinate[1], 'o')
    plt.text(coordinate[0] * (1 + 0.1), coordinate[1] * (1 - 0.1) , name)


# drawing Quadrilateral
drawLine(l1)
drawLine(l2)
drawLine(l3)
drawLine(l4)
drawLine(l5)
drawLine(l6)


# plotting vertices
drawVertix(F, "F")
drawVertix(L, "L")
drawVertix(I, "I")
drawVertix(T, "T")


plt.xlabel('x - axis')
plt.ylabel('y - axis')
plt.title('Quadrilateral')
plt.grid()
plt.show()